### ISSUE TITLE
Provide directory-helper-methods

### ISSUE THREAD

**Issue by TopperDEL** [storj/java-libstorj#10]
For my libstorj.NET-wrapper I want to provide methods to Access Folders and subfolders within buckets. There is an ongoing discussion about this [as a SIP here](https://github.com/Storj/sips/issues/19).

I Can do something within my wrapper, but then you would Need to do it on your side, too, and we have code-duplication with probably different implementation.

I suggest extending your API with the following methods:

GetContent(Bucket b)
=> should return direct subfolders and files within the bucket as e.g. a "Content-object".
=> a Content-object might have two lists: files and folders

Get Content(Folder f)
=> shoudl return direct subfolders and files within a Folder as e.g. a "Content-object" as described above.

Once the SIP is implemented, the Internat structure Can be mapped accordingly. For the current implementation this might also make a buffer necessary, so that the Content of a bucket does not get reloaded on every API-Access.

**Comment by kaloyan-raev** [comment]
@TopperDEL I created #11 with first iteration of a File Tree API. Take a look at `FileTreeExample.java` on how to print the complete file tree in a Storj account.

**Comment by TopperDEL** [comment]
Yes, that should be helpful for the start. Do you plan extending it? For reading the dir structure, this should be absolutely ok. For testing, I would Need new DLLs unfortunately. But take your time.

Thank you very much for your quick implementation!

**Comment by kaloyan-raev** [comment]
Yes, this is a first iteration. It will take a few more until we bake a good API for all operations.

Please, try it and give me some feedback of what improvements could be done.

I am attaching an updated JAR. No new DLLs are required as the change is only in the Java code.


[libstorj-java-0.9.zip](https://github.com/Storj/java-libstorj/files/1855163/libstorj-java-0.9.zip)

**Comment by TopperDEL** [comment]
Thank you! Will try this later today and Keep you updated.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
